### PR TITLE
Rocks 6.2 Comet

### PR DESCRIPTION
**Pull request by tcooper**
@ppapadopoulos, this PR will track changes implemented on Comet for upgrade. Cherry-pick to master what you feel is appropriate.

### CODE REVIEW

**Comment by samucaoo** [comment]
i cant download de older versions of rocks cluster, its any issue on the mirror? 

Like Rocks 6.2/6.1/6.0...

**Comment by nadyawilliams** [comment]
> i cant download de older versions of rocks cluster, its any issue on the mirror?
> 
> Like Rocks 6.2/6.1/6.0...

you can download *.tar.gz files form git and build if this is what you are after or you can download from the rocks website rocks clusters.org under downloads tab. Not sure what mirror are you referring to

**Comment by nadyawilliams** [comment]
> > i cant download de older versions of rocks cluster, its any issue on the mirror?
> > Like Rocks 6.2/6.1/6.0...
> 
> you can download *.tar.gz files form git and build if this is what you are after or you can download from the rocks website rocks clusters.org under downloads tab. Not sure what mirror are you referring to

Correction: you can still download 6.2 but not older.

**Comment by tcooper** [comment]
Rocks has moved on to version 7.0. PR is no longer valid.

**Pull request closed without merging**
